name = "Islander"
uuid = "a84d6206-b532-420f-96fe-6b90bdd740da"
authors = ["xzackli"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
